version: '3.3'

services:
    db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: cocorico_dev
       MYSQL_DATABASE: cocorico_dev
       MYSQL_USER: cocorico_dev
       MYSQL_PASSWORD: cocorico_dev
     ports:
       - 3306:3306
    php:
     depends_on:
       - db
       - mongodb
     image: cocolabs/cocorico
     ports:
       - "80:8000"
       - "9002:9001"
     # volumes:
     #  #- ./:/var/www/html
     environment:
       DB_HOST: db:3306
       DB_USER: cocorico_dev
       DB_PASSWORD: cocorico_dev
       DB_NAME: cocorico_dev
       APPLICATION_ENV: development
       REDIS_HOST: redis-master
    phpmyadmin:
      restart: 'no'
      image: phpmyadmin/phpmyadmin:4.6
      depends_on:
        - db
      ports:
        - "9090:80"
      environment:
        PMA_ARBITRARY: 1
        PMA_HOST: db
        PMA_PORT: 3306
        PMA_USER: root
        PMA_PASSWORD: gsviec
    mongodb:
      image: mongo:3.4
      volumes:
       - db_mongo:/data/db
volumes:
  db_data:
  db_mongo:
